xbmc/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets

from showcase.models import Movie


# Serializers define the API representation.
class MovieSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Movie
        fields = ('idmovie', 'c00', 'c01', 'c05', 'c06', 'c07', 'c08', 'c12', 'c14', 'c15', 'c21', )

# ViewSets define the view behavior.
class MovieViewSet(viewsets.ModelViewSet):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'movies', MovieViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
]

xbmc/showcase/urls.py
from django.conf.urls import url

from .views import ActorDetail, MovieDetail, MovieList


urlpatterns = (

    url(r'^movies/$', MovieList.as_view(), name='movie-list'),
    url(r'^movies/(?P<pk>\d+)/$', MovieDetail.as_view(), name='movie-detail'),
    
    url(r'^actors/(?P<pk>\d+)/$', ActorDetail.as_view(), name='actor-detail'),
)

xbmc/xbmc/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

#import xadmin
#xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
#from xadmin.plugins import xversion
#xversion.register_models()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xbmc.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^xadmin/', include(xadmin.site.urls)),
    # url(r'^admin_tools/', include('admin_tools.urls')),
    # url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^showcase/', include('showcase.urls', namespace='showcase')),
    url(r'^api/', include('api.urls')),
)

xbmc/showcase/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify

from django.conf import settings


class Actorlinkepisode(models.Model):
    idactor = models.IntegerField(db_column='idActor', primary_key=True) # Field name made lowercase.
    idepisode = models.IntegerField(db_column='idEpisode', blank=True, null=True) # Field name made lowercase.
    strrole = models.TextField(db_column='strRole', blank=True) # Field name made lowercase.
    iorder = models.IntegerField(db_column='iOrder', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'actorlinkepisode'
        unique_together = (('idactor', 'idepisode'),)


class Actorlinktvshow(models.Model):
    idactor = models.IntegerField(db_column='idActor', primary_key=True) # Field name made lowercase.
    idshow = models.IntegerField(db_column='idShow', blank=True, null=True) # Field name made lowercase.
    strrole = models.TextField(db_column='strRole', blank=True) # Field name made lowercase.
    iorder = models.IntegerField(db_column='iOrder', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'actorlinktvshow'
        unique_together = (('idactor', 'idshow'),)

class Actors(models.Model):
    idactor = models.IntegerField(db_column='idActor', primary_key=True, blank=True) # Field name made lowercase.
    stractor = models.TextField(db_column='strActor', blank=True) # Field name made lowercase.
    strthumb = models.TextField(db_column='strThumb', blank=True) # Field name made lowercase.
    def __unicode__(self):
        return self.stractor
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'actors'

class Art(models.Model):
    art_id = models.IntegerField(primary_key=True, blank=True)
    media_id = models.IntegerField(blank=True, null=True)
    media_type = models.TextField(blank=True)
    type = models.TextField(blank=True)
    url = models.TextField(blank=True)
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'art'

class Artistlinkmusicvideo(models.Model):
    idartist = models.IntegerField(db_column='idArtist', primary_key=True) # Field name made lowercase.
    idmvideo = models.IntegerField(db_column='idMVideo', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'artistlinkmusicvideo'
        unique_together = (('idartist', 'idmvideo'),)

class Bookmark(models.Model):
    idbookmark = models.IntegerField(db_column='idBookmark', primary_key=True, blank=True) # Field name made lowercase.
    idfile = models.IntegerField(db_column='idFile', blank=True, null=True) # Field name made lowercase.
    timeinseconds = models.TextField(db_column='timeInSeconds', blank=True) # Field name made lowercase. This field type is a guess.
    totaltimeinseconds = models.TextField(db_column='totalTimeInSeconds', blank=True) # Field name made lowercase. This field type is a guess.
    thumbnailimage = models.TextField(db_column='thumbNailImage', blank=True) # Field name made lowercase.
    player = models.TextField(blank=True)
    playerstate = models.TextField(db_column='playerState', blank=True) # Field name made lowercase.
    type = models.IntegerField(blank=True, null=True)
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'bookmark'

class Country(models.Model):
    idcountry = models.IntegerField(db_column='idCountry', primary_key=True, blank=True) # Field name made lowercase.
    strcountry = models.TextField(db_column='strCountry', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'country'

class Countrylinkmovie(models.Model):
    idcountry = models.IntegerField(db_column='idCountry', primary_key=True) # Field name made lowercase.
    idmovie = models.IntegerField(db_column='idMovie', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'countrylinkmovie'
        unique_together = (('idcountry', 'idmovie'),)


class Episode(models.Model):
    idepisode = models.IntegerField(db_column='idEpisode', primary_key=True, blank=True) # Field name made lowercase.
    idfile = models.IntegerField(db_column='idFile', blank=True, null=True) # Field name made lowercase.
    c00 = models.TextField(blank=True)
    c01 = models.TextField(blank=True)
    c02 = models.TextField(blank=True)
    c03 = models.TextField(blank=True)
    c04 = models.TextField(blank=True)
    c05 = models.TextField(blank=True)
    c06 = models.TextField(blank=True)
    c07 = models.TextField(blank=True)
    c08 = models.TextField(blank=True)
    c09 = models.TextField(blank=True)
    c10 = models.TextField(blank=True)
    c11 = models.TextField(blank=True)
    c12 = models.CharField(max_length=24, blank=True)
    c13 = models.CharField(max_length=24, blank=True)
    c14 = models.TextField(blank=True)
    c15 = models.TextField(blank=True)
    c16 = models.TextField(blank=True)
    c17 = models.CharField(max_length=24, blank=True)
    c18 = models.TextField(blank=True)
    c19 = models.TextField(blank=True)
    c20 = models.TextField(blank=True)
    c21 = models.TextField(blank=True)
    c22 = models.TextField(blank=True)
    c23 = models.TextField(blank=True)
    idshow = models.IntegerField(db_column='idShow', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'episode'

class Files(models.Model):
    idfile = models.IntegerField(db_column='idFile', primary_key=True, blank=True) # Field name made lowercase.
    idpath = models.IntegerField(db_column='idPath', blank=True, null=True) # Field name made lowercase.
    strfilename = models.TextField(db_column='strFilename', blank=True) # Field name made lowercase.
    playcount = models.IntegerField(db_column='playCount', blank=True, null=True) # Field name made lowercase.
    lastplayed = models.TextField(db_column='lastPlayed', blank=True) # Field name made lowercase.
    dateadded = models.TextField(db_column='dateAdded', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'files'

class Genre(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True, blank=True) # Field name made lowercase.
    strgenre = models.TextField(db_column='strGenre', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genre'

class Genrelinkmovie(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True) # Field name made lowercase.
    idmovie = models.IntegerField(db_column='idMovie', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genrelinkmovie'
        unique_together = (('idgenre', 'idmovie'),)

class Genrelinkmusicvideo(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True) # Field name made lowercase.
    idmvideo = models.IntegerField(db_column='idMVideo', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genrelinkmusicvideo'
        unique_together = (('idgenre', 'idmvideo'),)

class Genrelinktvshow(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True) # Field name made lowercase.
    idshow = models.IntegerField(db_column='idShow', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genrelinktvshow'
        unique_together = (('idgenre', 'idshow'),)

class Sets(models.Model):
    idset = models.IntegerField(db_column='idSet', primary_key=True, blank=True) # Field name made lowercase.
    strset = models.TextField(db_column='strSet', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'sets'

class Movie(models.Model):
    idmovie = models.IntegerField(db_column='idMovie', primary_key=True, blank=True) # Field name made lowercase.
    #idfile = models.IntegerField(db_column='idFile', blank=True, null=True) # Field name made lowercase.
    file = models.ForeignKey(Files, db_column='idFile')
    c00 = models.TextField(blank=True)
    c01 = models.TextField(blank=True)
    c02 = models.TextField(blank=True)
    c03 = models.TextField(blank=True)
    c04 = models.TextField(blank=True)
    c05 = models.TextField(blank=True)
    c06 = models.TextField(blank=True)
    c07 = models.TextField(blank=True)
    c08 = models.TextField(blank=True)
    c09 = models.TextField(blank=True)
    c10 = models.TextField(blank=True)
    c11 = models.TextField(blank=True)
    c12 = models.TextField(blank=True)
    c13 = models.TextField(blank=True)

xbmc/showcase/views.py
from django.views.generic import DetailView, ListView

from .models import Actors, Movie


class MovieList(ListView):
    model = Movie
    context_object_name = 'movie_list'
    paginate_by = 20


class MovieDetail(DetailView):
    model = Movie


class ActorDetail(DetailView):
	model = Actors
	context_object_name = 'actor'

xbmc/showcase/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block metatitle %}Welcome{% endblock %} &mdash; Django XBMC</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">

	<!-- Optional theme -->
	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css">

	<!-- Latest compiled and minified JavaScript -->
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js" defer></script>
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js" defer></script>
	<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.3.5/angular.min.js"></script>
	<style type="text/css">
body {
  padding-top: 70px;
  padding-bottom: 30px;
}
	</style>
</head>
<body data-ng-app="">

	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">xbmc</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li class="active"><a href="{% url 'showcase:movie-list' %}">Movies</a></li>

			{% comment %}

            <li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><a href="#">Action</a></li>
                <li><a href="#">Another action</a></li>
                <li><a href="#">Something else here</a></li>
                <li class="divider"></li>
                <li class="dropdown-header">Nav header</li>
                <li><a href="#">Separated link</a></li>
                <li><a href="#">One more separated link</a></li>
              </ul>
            </li>

			{% endcomment %}

          </ul>

          {% comment %}
          
          <ul class="nav navbar-nav navbar-right">
            <li><a href="../navbar/">Default</a></li>
            <li><a href="../navbar-static-top/">Static top</a></li>
            <li class="active"><a href="./">Fixed top <span class="sr-only">(current)</span></a></li>
          </ul>
          
          {% endcomment %}

        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

	  {% block content %}{% endblock %}

    </div>


	
</body>
</html>