xbmc/api/urls.py
from django.conf.urls import url, include
from rest_framework import routers, serializers, viewsets

from showcase.models import Movie


# Serializers define the API representation.
class MovieSerializer(serializers.HyperlinkedModelSerializer):
    class Meta:
        model = Movie
        fields = ('idmovie', 'c00', 'c01', 'c05', 'c06', 'c07', 'c08', 'c12', 'c14', 'c15', 'c21', )

# ViewSets define the view behavior.
class MovieViewSet(viewsets.ModelViewSet):
    queryset = Movie.objects.all()
    serializer_class = MovieSerializer

# Routers provide an easy way of automatically determining the URL conf.
router = routers.DefaultRouter()
router.register(r'movies', MovieViewSet)


urlpatterns = [
    url(r'^', include(router.urls)),
    url(r'^auth/', include('rest_framework.urls', namespace='rest_framework'))
]

xbmc/showcase/urls.py
from django.conf.urls import url

from .views import ActorDetail, MovieDetail, MovieList


urlpatterns = (

    url(r'^movies/$', MovieList.as_view(), name='movie-list'),
    url(r'^movies/(?P<pk>\d+)/$', MovieDetail.as_view(), name='movie-detail'),
    
    url(r'^actors/(?P<pk>\d+)/$', ActorDetail.as_view(), name='actor-detail'),
)

xbmc/xbmc/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

#import xadmin
#xadmin.autodiscover()

# version模块自动注册需要版本控制的 Model
#from xadmin.plugins import xversion
#xversion.register_models()


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'xbmc.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    # url(r'^xadmin/', include(xadmin.site.urls)),
    # url(r'^admin_tools/', include('admin_tools.urls')),
    # url(r'^grappelli/', include('grappelli.urls')), # grappelli URLS
    url(r'^admin/', include(admin.site.urls)),
    url(r'^showcase/', include('showcase.urls', namespace='showcase')),
    url(r'^api/', include('api.urls')),
)

xbmc/showcase/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Remove `managed = False` lines if you wish to allow Django to create and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
#
# Also note: You'll have to insert the output of 'django-admin.py sqlcustom [appname]'
# into your database.
from __future__ import unicode_literals

from django.db import models
from django.utils.text import slugify

from django.conf import settings


class Actorlinkepisode(models.Model):
    idactor = models.IntegerField(db_column='idActor', primary_key=True) # Field name made lowercase.
    idepisode = models.IntegerField(db_column='idEpisode', blank=True, null=True) # Field name made lowercase.
    strrole = models.TextField(db_column='strRole', blank=True) # Field name made lowercase.
    iorder = models.IntegerField(db_column='iOrder', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'actorlinkepisode'
        unique_together = (('idactor', 'idepisode'),)


class Actorlinktvshow(models.Model):
    idactor = models.IntegerField(db_column='idActor', primary_key=True) # Field name made lowercase.
    idshow = models.IntegerField(db_column='idShow', blank=True, null=True) # Field name made lowercase.
    strrole = models.TextField(db_column='strRole', blank=True) # Field name made lowercase.
    iorder = models.IntegerField(db_column='iOrder', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'actorlinktvshow'
        unique_together = (('idactor', 'idshow'),)

class Actors(models.Model):
    idactor = models.IntegerField(db_column='idActor', primary_key=True, blank=True) # Field name made lowercase.
    stractor = models.TextField(db_column='strActor', blank=True) # Field name made lowercase.
    strthumb = models.TextField(db_column='strThumb', blank=True) # Field name made lowercase.
    def __unicode__(self):
        return self.stractor
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'actors'

class Art(models.Model):
    art_id = models.IntegerField(primary_key=True, blank=True)
    media_id = models.IntegerField(blank=True, null=True)
    media_type = models.TextField(blank=True)
    type = models.TextField(blank=True)
    url = models.TextField(blank=True)
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'art'

class Artistlinkmusicvideo(models.Model):
    idartist = models.IntegerField(db_column='idArtist', primary_key=True) # Field name made lowercase.
    idmvideo = models.IntegerField(db_column='idMVideo', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'artistlinkmusicvideo'
        unique_together = (('idartist', 'idmvideo'),)

class Bookmark(models.Model):
    idbookmark = models.IntegerField(db_column='idBookmark', primary_key=True, blank=True) # Field name made lowercase.
    idfile = models.IntegerField(db_column='idFile', blank=True, null=True) # Field name made lowercase.
    timeinseconds = models.TextField(db_column='timeInSeconds', blank=True) # Field name made lowercase. This field type is a guess.
    totaltimeinseconds = models.TextField(db_column='totalTimeInSeconds', blank=True) # Field name made lowercase. This field type is a guess.
    thumbnailimage = models.TextField(db_column='thumbNailImage', blank=True) # Field name made lowercase.
    player = models.TextField(blank=True)
    playerstate = models.TextField(db_column='playerState', blank=True) # Field name made lowercase.
    type = models.IntegerField(blank=True, null=True)
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'bookmark'

class Country(models.Model):
    idcountry = models.IntegerField(db_column='idCountry', primary_key=True, blank=True) # Field name made lowercase.
    strcountry = models.TextField(db_column='strCountry', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'country'

class Countrylinkmovie(models.Model):
    idcountry = models.IntegerField(db_column='idCountry', primary_key=True) # Field name made lowercase.
    idmovie = models.IntegerField(db_column='idMovie', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'countrylinkmovie'
        unique_together = (('idcountry', 'idmovie'),)


class Episode(models.Model):
    idepisode = models.IntegerField(db_column='idEpisode', primary_key=True, blank=True) # Field name made lowercase.
    idfile = models.IntegerField(db_column='idFile', blank=True, null=True) # Field name made lowercase.
    c00 = models.TextField(blank=True)
    c01 = models.TextField(blank=True)
    c02 = models.TextField(blank=True)
    c03 = models.TextField(blank=True)
    c04 = models.TextField(blank=True)
    c05 = models.TextField(blank=True)
    c06 = models.TextField(blank=True)
    c07 = models.TextField(blank=True)
    c08 = models.TextField(blank=True)
    c09 = models.TextField(blank=True)
    c10 = models.TextField(blank=True)
    c11 = models.TextField(blank=True)
    c12 = models.CharField(max_length=24, blank=True)
    c13 = models.CharField(max_length=24, blank=True)
    c14 = models.TextField(blank=True)
    c15 = models.TextField(blank=True)
    c16 = models.TextField(blank=True)
    c17 = models.CharField(max_length=24, blank=True)
    c18 = models.TextField(blank=True)
    c19 = models.TextField(blank=True)
    c20 = models.TextField(blank=True)
    c21 = models.TextField(blank=True)
    c22 = models.TextField(blank=True)
    c23 = models.TextField(blank=True)
    idshow = models.IntegerField(db_column='idShow', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'episode'

class Files(models.Model):
    idfile = models.IntegerField(db_column='idFile', primary_key=True, blank=True) # Field name made lowercase.
    idpath = models.IntegerField(db_column='idPath', blank=True, null=True) # Field name made lowercase.
    strfilename = models.TextField(db_column='strFilename', blank=True) # Field name made lowercase.
    playcount = models.IntegerField(db_column='playCount', blank=True, null=True) # Field name made lowercase.
    lastplayed = models.TextField(db_column='lastPlayed', blank=True) # Field name made lowercase.
    dateadded = models.TextField(db_column='dateAdded', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'files'

class Genre(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True, blank=True) # Field name made lowercase.
    strgenre = models.TextField(db_column='strGenre', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genre'

class Genrelinkmovie(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True) # Field name made lowercase.
    idmovie = models.IntegerField(db_column='idMovie', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genrelinkmovie'
        unique_together = (('idgenre', 'idmovie'),)

class Genrelinkmusicvideo(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True) # Field name made lowercase.
    idmvideo = models.IntegerField(db_column='idMVideo', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genrelinkmusicvideo'
        unique_together = (('idgenre', 'idmvideo'),)

class Genrelinktvshow(models.Model):
    idgenre = models.IntegerField(db_column='idGenre', primary_key=True) # Field name made lowercase.
    idshow = models.IntegerField(db_column='idShow', blank=True, null=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'genrelinktvshow'
        unique_together = (('idgenre', 'idshow'),)

class Sets(models.Model):
    idset = models.IntegerField(db_column='idSet', primary_key=True, blank=True) # Field name made lowercase.
    strset = models.TextField(db_column='strSet', blank=True) # Field name made lowercase.
    class Meta:
        if settings.XBMC_MODELS_UNMANAGED:
            managed = False
        db_table = 'sets'

class Movie(models.Model):
    idmovie = models.IntegerField(db_column='idMovie', primary_key=True, blank=True) # Field name made lowercase.
    #idfile = models.IntegerField(db_column='idFile', blank=True, null=True) # Field name made lowercase.
    file = models.ForeignKey(Files, db_column='idFile')
    c00 = models.TextField(blank=True)
    c01 = models.TextField(blank=True)
    c02 = models.TextField(blank=True)
    c03 = models.TextField(blank=True)
    c04 = models.TextField(blank=True)
    c05 = models.TextField(blank=True)
    c06 = models.TextField(blank=True)
    c07 = models.TextField(blank=True)
    c08 = models.TextField(blank=True)
    c09 = models.TextField(blank=True)
    c10 = models.TextField(blank=True)
    c11 = models.TextField(blank=True)
    c12 = models.TextField(blank=True)
    c13 = models.TextField(blank=True)

xbmc/showcase/views.py
from django.views.generic import DetailView, ListView

from .models import Actors, Movie


class MovieList(ListView):
    model = Movie
    context_object_name = 'movie_list'
    paginate_by = 20


class MovieDetail(DetailView):
    model = Movie


class ActorDetail(DetailView):
	model = Actors
	context_object_name = 'actor'

xbmc/showcase/templates/showcase/actors_detail.html
{% extends 'base.html' %}

{% block content %}

<div class="page-header">
    <h1>{{ actor.stractor }}</h1>
</div>

<div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12">

		Acted:
		<ul>
		{% for link in actor.actorlinkmovie_set.all %}
			<li>{{ link.movie.c00 }} ({{ link.movie.c07 }}) &dash; {{ link.strrole }}</li>
		{% endfor %}
		</ul>


		Directed:
		<ul>
		{% for movie in actor.movies_directed.all %}
			<li>{{ movie.c00 }}</li>
		{% endfor %}
		</ul>

		Written:
		<ul>
		{% for movie in actor.movies_written.all %}
			<li>
			<a href="{% url 'showcase:movie-detail' pk=movie.idmovie %}">
			{{ movie.c00 }}
			</a>
			</li>
		{% endfor %}
		</ul>

	</div>

</div>

{% endblock %}

xbmc/showcase/templates/showcase/movie_detail.html
{% extends 'base.html' %}

{% load staticfiles %}
{% load showcase_extras %}

{% block metatitle %}{{ object.c00 }} ({{ object.c07 }}){% endblock  %}

{% block content %}

<div class="page-header">
    <h1>{{ object.c00 }} ({{ object.c07 }})
    <small>{{object.c03}}</small></h1>
</div>


<div class="row">
    
    <div class="col-xs-4 col-sm-5 col-md-4">
        <img src="http://image.tmdb.org/t/p/w300/{{ object.c08|thumbs|first }}.jpg" data-holder-rendered="true" class="img-responsive">

      <h3>Stream details</h3>
      <p>

          {% regroup object.file.streamdetails_set.all by istreamtype as streaminfo %}


          {% for info in streaminfo %}

          {% if info.grouper == 0 %}

          <h5>
            Video
          </h5>

          <ul>
            {% for video in info.list %}
            <li>{{ video.strvideocodec }} ({{ video.ivideowidth }} x {{ video.ivideoheight }} with aspect {{ video.fvideoaspect }})</li>
            {% endfor %}
          </ul>

          {% endif %}

          {% if info.grouper == 1 %}
          <h5>
            Audio
          </h5>

          <ul>
            {% for video in info.list %}
            <li>{{ video.straudiolanguage }} ({{ video.straudiocodec }}) </li>
            {% endfor %}
          </ul>
          {% endif %}

          {% if info.grouper == 2 %}

          <h5>
            Subs
          </h5>

          <ul>
            {% for video in info.list %}
            <li>{{ video.strsubtitlelanguage }}</li>
            {% endfor %}
          </ul>

          {% endif %}

          {% endfor %}

      </p>

    </div>


    <div class="col-xs-8 col-sm-7 col-md-8">
        <p class="lead">{{ object.c01 }}</p>

        <dl class="dl-horizontal">

          <dt>Directed</dt>
          {% comment %}
          <dd>{{ object.c15 }}</dd>
          {% endcomment %}

          <dd>
          {% for director in object.directors.all %}
          <a href="{% url 'showcase:actor-detail' pk=director.idactor %}">{{ director.stractor }}</a>{% if not forloop.last %}, {% endif %}
          {% empty %}
          Not available
          {% endfor %}
          </dd>
          
          <dt>Written</dt>
          {% comment %}
          <dd>{{ object.c06 }}</dd>
          {{ object.writers.all|join:", "}} 
          {% endcomment %}

          <dd>
          {% for writer in object.writers.all %}
          <a href="{% url 'showcase:actor-detail' pk=writer.idactor %}">{{ writer.stractor }}</a>{% if not forloop.last %}, {% endif %}
          {% empty %}
          Not available
          {% endfor %}
          </dd>

          <dt>Rating</dt>
          <dd>{{ object.c12 }}</dd>

          <dt>Genre</dt>
          <dd>{{ object.c14 }}</dd>

          <dt>Country</dt>
          <dd>{{ object.c21 }}</dd>

        </dl>

    </div>



    {% with youtube_video_id=object.c19|youtube|first %}
    {% if youtube_video_id %}
    <div class="col-xs-8 col-sm-7 col-md-8">
      <div class="embed-responsive embed-responsive-16by9">
        <iframe class="embed-responsive-item" src="//www.youtube.com/embed/{{ youtube_video_id }}?rel=0"></iframe>
      </div>
    </div>
    {% endif %}
    {% endwith %}
    


{% endblock %}


</div>


{% comment %}
    <div id="carousel-example-generic" class="carousel slide col-md-3 " data-ride="carousel">

      <ol class="carousel-indicators">
        {% for image_id in object.c08|thumbs|slice:":4" %}
        <li data-target="#carousel-example-generic" data-slide-to="{{ forloop.counter0 }}" class=""></li>
        {% endfor%}
      </ol>

      <div class="carousel-inner" role="listbox">
        {% for image_id in object.c08|thumbs|slice:":4" %}
        <div class="item {% if forloop.first %}active{% endif %}">
          <img src="http://cf2.imgobject.com/t/p/w185/{{ image_id}}.jpg" data-holder-rendered="true">
        </div>
        {% endfor%}
      </div>

      <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>

    

</div>

    
    <div class="row">
          {% for image_id in object.c08|thumbs|slice:":4" %}
      <div class="col-xs-6 col-md-3">
        <a href="#" class="thumbnail">
          <img src="http://cf2.imgobject.com/t/p/w185/{{ image_id}}.jpg" alt="...">
        </a>
      </div>
          {% endfor%}

    </div>
    {% endcomment %}

xbmc/showcase/templates/showcase/movie_list.html
{% extends 'base.html' %}

{% block content %}
<table class="table table-hover">
  <tr>
    <th>Title</th>
    <th>Year</th>
    <th>Directed by</th>
    <th>Rating</th>
  </tr>
	{% for movie in movie_list %}
	<tr>
    <td>
      <a href="{% url 'showcase:movie-detail' movie.idmovie %}">{{ movie.c00 }}</a>
    </td>
    <td>{{ movie.c07 }}</td>
    <td>
      {{ movie.c15 }}
    </td>
    <td>{{ movie.c05|floatformat:1 }}</td>
	</tr>
	{% endfor %}
</table>

{% comment %}

{% if page_obj.has_previous %}
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
{% endif %}


<span class="current">
    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
</span>

{% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
{% endif %}

{% endcomment %}

<nav>
  <ul class="pager">
  	{% if page_obj.has_previous %}
    <li class="previous"><a href="?page={{ page_obj.previous_page_number }}"><span aria-hidden="true">&larr;</span> Newer</a></li>
    {% endif %}
    {% if page_obj.has_next %}
    <li class="next"><a href="?page={{ page_obj.next_page_number }}">Older <span aria-hidden="true">&rarr;</span></a></li>
    {% endif %}
  </ul>
</nav>

{% endblock %}